[project]
name = "jax-qec"
version = "0.0.1"
description = "JAX-based quantum error correction toolkit"
authors = [
    { name="Arsh Noman", email="arshnoman2270@gmail.com" }
]
dependencies = [
    "jax"
]